#pragma once

// i REALLY need to organize this..

#define SYSCALL_GET_TASK_ID 1
#define SYSCALL_EXIT  2
#define SYSCALL_PRINT 3
#define SYSCALL_EXEC  4
#define SYSCALL_OPEN_FILE   5
#define SYSCALL_CLOSE_FILE  6
#define SYSCALL_READ_FILE   7
#define SYSCALL_GET_FILE_SIZE 8
#define SYSCALL_SHMEM_CREATE 9
#define SYSCALL_SHMEM_DESTROY 10
#define SYSCALL_SHMEM_EXISTS 11
#define SYSCALL_SHMEM_MAP 12
#define SYSCALL_SHMEM_UNMAP 13
#define SYSCALL_GET_EVENT_BUFFER_SHMEM_ID 14
#define SYSCALL_CREATE_WINDOW 15
#define SYSCALL_DESTROY_WINDOW 16
#define SYSCALL_GET_WINDOW_FB_SHMEM_ID 17
#define SYSCALL_WINDOW_SWAP_BUFFERS 18
#define SYSCALL_WAIT_FOR_EVENT 19
#define SYSCALL_SET_WINDOW_TITLE 20
#define SYSCALL_GET_HEAP_START 21
#define SYSCALL_GET_HEAP_END 22
#define SYSCALL_SET_HEAP_END 23
#define SYSCALL_OPEN_DIR 24
#define SYSCALL_CLOSE_DIR 25
#define SYSCALL_NEXT_FILE_IN_DIR 26
#define SYSCALL_SET_TIMER_INTERVAL 27
#define SYSCALL_DEBUG 28
#define SYSCALL_GET_TASK_INFO 29
#define SYSCALL_PRINT_CHAR 30
#define SYSCALL_GET_FILE_OFFSET 31
#define SYSCALL_SET_FILE_OFFSET 32
#define SYSCALL_GET_SYSTEM_TIME 33
#define SYSCALL_WRITE_FILE 34
