#pragma once

// basics
#define SYSCALL_EXIT            1
#define SYSCALL_EXEC            2
#define SYSCALL_PRINT           3
#define SYSCALL_PRINT_CHAR      4
#define SYSCALL_GET_TASK_ID     5
#define SYSCALL_GET_TASK_INFO   6
#define SYSCALL_GET_SYSTEM_TIME 7

// file io
#define SYSCALL_OPEN_FILE        100
#define SYSCALL_CLOSE_FILE       101
#define SYSCALL_READ_FILE        102
#define SYSCALL_WRITE_FILE       103
#define SYSCALL_GET_FILE_SIZE    104
#define SYSCALL_OPEN_DIR         105
#define SYSCALL_CLOSE_DIR        106
#define SYSCALL_NEXT_FILE_IN_DIR 107
#define SYSCALL_GET_FILE_OFFSET  108
#define SYSCALL_SET_FILE_OFFSET  109

// shared memory
#define SYSCALL_SHMEM_CREATE  200
#define SYSCALL_SHMEM_DESTROY 201
#define SYSCALL_SHMEM_EXISTS  202
#define SYSCALL_SHMEM_MAP     203
#define SYSCALL_SHMEM_UNMAP   204

// events
#define SYSCALL_GET_EVENT_BUFFER_SHMEM_ID 300
#define SYSCALL_WAIT_FOR_EVENT            301
#define SYSCALL_SET_TIMER_INTERVAL        302

// window management
#define SYSCALL_CREATE_WINDOW          400
#define SYSCALL_DESTROY_WINDOW         401
#define SYSCALL_GET_WINDOW_FB_SHMEM_ID 402
#define SYSCALL_WINDOW_SWAP_BUFFERS    403
#define SYSCALL_SET_WINDOW_TITLE       404

// user heap
#define SYSCALL_GET_HEAP_START 500
#define SYSCALL_GET_HEAP_END   501
#define SYSCALL_SET_HEAP_END   502

// other
#define SYSCALL_DEBUG 999
